config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, only: %i[sign_in sign_out session]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get 'about', to: 'home#about'
  get '/infiniteScrolling', to: "posts#infiniteScrolling"

  devise_for :doctors, controolers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    passwords: 'patients/passwords',
    registrations: 'patients/registrations'
  }

  resource :patient, only: %i[show]
  resources :doctors, only: %i[show update]
  resources :posts
  resources :opinions, :patient_comments, :doctor_comments, only: %i[create update destroy]
  resources :hospitals

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :hospital
  belongs_to :department
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :categorizations
  has_many :hospitals, through: :categorizations
  has_many :posts
  has_many :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :opinions
  has_many :doctor_comments
  belongs_to :department
  belongs_to :hospital, optional: true

  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, :registration_number, :registration_date, presence: true
end

app/models/doctor_comment.rb
class DoctorComment < ApplicationRecord
  belongs_to :doctor
  belongs_to :opinion

  validates :content, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :doctors
  has_many :categorizations
  has_many :departments, through: :categorizations
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, :name_kana, :founder, :founder_kana, :administer, :administer_kana, :post_code, :prefecture, :address, :phone_number, presence: true

  include JpPrefecture
  jp_prefecture :prefecture, method_name: :pref

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :post
  belongs_to :doctor
  has_many :doctor_comments
  has_many :patient_comments

  validates :content, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts
  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, presence: true
  validates :phone_number, length: { in: 10..13 }
end

app/models/patient_comment.rb
class PatientComment < ApplicationRecord
  belongs_to :patient
  belongs_to :opinion

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :patient
  belongs_to :department
  has_many :opinions
  mount_uploaders :refferal, ImageUploader
  serialize :refferal, JSON

  validates :refferal, :desease_name, :detail, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    @doctor = Doctor.find(params[:id])
  end

  def update
    current_doctor.update(doctor_params)
    redirect_to current_doctor
  end

  private
    def doctor_params
      params.require(:doctor).permit(:hospital_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :authenticate_doctor!

  def create
    opinion = Opinion.new(opinion_params)
    opinion.doctor_id = current_doctor.id
    opinion.save
    redirect_to post_path(opinion.post_id)
  end

  def edit
    @opinion = Opinion.find(params[:id])
  end

  def update
    @opinion = Opinion.find(params[:id])
    @opinion.update(opinion_params)
    redirect_to post_path(@opinion.post_id)
  end

  def destroy
    opinion = Opinion.find(params[:id])
    opinion.destroy
  end

  private
    def opinion_params
      params.require(:opinion).permit(:content, :post_id)
    end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true
class PostsController < ApplicationController
  before_action :authenticate_patient!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(id: "desc").paginate(page: params[:page], per_page: 5)
    @top = "オピニオン依頼一覧"
    if params[:q].present?
      if params[:q][:department_id_eq].present?
      @top = Department.find(params[:q][:department_id_eq]).name + "のオピニオン依頼"
      end
    else
      @top = "オピニオン依頼一覧"
    end
  end

  def show
    @post = Post.find(params[:id])
    @q = Post.ransack(params[:q])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.patient_id = current_patient.id
    @post.department_id = 1
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def infiniteScrolling
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.js
    end
  end

  private
    def post_params
      params.require(:post).permit(:desease_name, :detail, :patient_id, :department_id, refferal: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

  def age
    d1=self.date_of_birth.strftime("%Y%m%d").to_i
    d2=Date.today.strftime("%Y%m%d").to_i
    return (d2 - d1) / 10000
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/opinions/_opinion.html.erb
<div class="opinion-box">
  <div class="opinion__prof-box">
    <%= image_tag opinion.doctor.image.thumb.to_s, class:"opinion__image" %>
    <div class="opinion__name-box">
      <h1 class="opinion__name"><%= link_to hospital_path(opinion.doctor.hospital) do %><%= opinion.doctor.family_name + ' ' + opinion.doctor.first_name %> <small>-<%= opinion.doctor.hospital.name %>-</small><% end %></h1>
      <p class="opinion__time"><%= opinion.created_at.to_s(:datetime) %></p>
    </div>
  </div>
  <div class="opinion__content-box">
    <p class="opinion__content"><%= safe_join(opinion.content.split("\n"),tag(:br)) %></p>
    <% if doctor_signed_in? %>
      <% if opinion.doctor_id == current_doctor.id %>
        <p class="opinion__edit post-button opinion-edit__toggle-<%= opinion.id %>">編集</p>
        <div class="opinion-edit__form-<%= opinion.id %> form-toggle text-area__wrapper"style="margin: 0 1rem;">
          <%= form_with model: opinion, url: opinion_path(opinion), local: true do |f| %>
            <div class="field">
              <%= f.text_area :content, placeholder:"内容" %>
              <%= f.label :content, '内容', class:"label" %>
            </div>
            <%= f.submit '送信', class:"button-default" %>
          <% end %>
        </div>

      <% end %>
    <% end %>
  </div>
  <div class="opinion__comment-box">
    <p class="opinion__comment-size">コメント数： <%= opinion.doctor_comments.size + opinion.patient_comments.size %>件</p>
    <% (opinion.patient_comments + opinion.doctor_comments).sort_by{|record| record.created_at}.each do |comment| %>
      <% if comment.class == DoctorComment %>
        <div class="opinion__comment">
          <h1 class="opinion__comment__name"><%= comment.doctor.family_name + ' ' + comment.doctor.first_name %></h1>
          <p class="opinion__comment__time"><%= comment.created_at.to_s(:datetime) %></p>
          <p class="opinion__comment__content"><%= safe_join(comment.content.split("\n"),tag(:br)) %></p>
          <% if doctor_signed_in? %>
            <% if comment.doctor_id == current_doctor.id %>
              <p class="opinion__comment__edit post-button opinion__comment-edit__toggle-<%= comment.id %>">編集</p>
              <div class="opinion__comment-edit__form-<%= comment.id %> form-toggle">
                <div class="text-area__wrapper">
                  <%= form_with model: comment, url: doctor_comment_path(comment), local: true do |c| %>
                  <div class="field">
                    <%= c.text_area :content, placeholder: '内容' %>
                    <%= c.label :content, "内容", class:"label" %>
                  </div>
                  <%= c.submit '送信', class:"button-default" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% elsif comment.class == PatientComment %>
        <div class="opinion__comment">
          <h1 class="opinion__comment__name"><%= comment.patient.family_name + ' ' + comment.patient.first_name %></h1>
          <p class="opinion__comment__time"><%= comment.created_at.to_s(:datetime) %></p>
          <p class="opinion__comment__content"><%= safe_join(comment.content.split("\n"),tag(:br)) %></p>
          <% if patient_signed_in? %>
            <% if comment.patient_id == current_patient.id %>
              <p class="opinion__comment__edit post-button opinion__comment-edit__toggle-<%= comment.id %>">編集</p>
              <div class="opinion__comment-edit__form-<%= comment.id %> form-toggle">
                <div class="text-area__wrapper">
                  <%= form_with model: comment, url: patient_comment_path(comment), local: true do |c| %>
                  <div class="field">
                    <%= c.text_area :content, placeholder:"内容" %>
                    <%= c.label :content, "内容", class:"label" %>
                  </div>
                  <%= c.submit '送信', class:"button-default" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      <% end %>
      <script>
        $('.opinion__comment-edit__toggle-<%= comment.id %>').click(function() {
          $('.opinion__comment-edit__form-<%= comment.id %>').slideToggle(10);
        })
      </script>
    <% end %>
  </div>
  <% if doctor_signed_in? %>
    <div class="opinion__comment__toggle-<%= opinion.id %>">
      <p class="post-info__comment-box">
        <span>コメントを投稿する</span>
        <span class="comment-button"><i class="fas fa-edit"></i></span>
      </p>
    </div>
    <div class="opinion__comment__form-<%= opinion.id %> form-toggle">
      <div class="text-area__wrapper">
        <%= form_with model: DoctorComment.new, local: true do |c| %>
          <div class="field">
            <%= c.text_area :content, placeholder: "コメント内容" %>
            <%= c.label :content, "コメント内容", class:"label" %>
          </div>
          <%= c.hidden_field :opinion_id, value: opinion.id %>
          <%= c.submit '送信', class:"button-default" %>
        <% end %>
      </div>
    </div>
  <% elsif patient_signed_in? %>
    <div class="opinion__comment__toggle-<%= opinion.id %>">
      <p class="post-info__comment-box">
        <span>コメントを投稿する</span>
        <span class="comment-button"><i class="fas fa-edit"></i></span>
      </p>
    </div>
    <div class="opinion__comment__form-<%= opinion.id %> form-toggle">
      <div class="text-area__wrapper">
        <%= form_with model: PatientComment.new, local: true do |c| %>
          <div class="field">
            <%= c.text_area :content, placeholder:"コメント内容" %>
            <%= c.label :content, "コメント内容", class:"label" %>
          </div>
          <%= c.hidden_field :opinion_id, value: opinion.id %>
          <%= c.submit '送信', class:"button-default" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<script>
    $('.opinion__comment__toggle-<%= opinion.id %>').click(function() {
        $('.opinion__comment__form-<%= opinion.id %>').slideToggle(10);
    })
    $('.opinion-edit__toggle-<%= opinion.id %>').click(function() {
        $('.opinion-edit__form-<%= opinion.id %>').slideToggle(10);
    })
</script>