config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, only: %i[sign_in sign_out session]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get 'about', to: 'home#about'
  get '/infiniteScrolling', to: "posts#infiniteScrolling"

  devise_for :doctors, controolers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    passwords: 'patients/passwords',
    registrations: 'patients/registrations'
  }

  resource :patient, only: %i[show]
  resources :doctors, only: %i[show update]
  resources :posts
  resources :opinions, :patient_comments, :doctor_comments, only: %i[create update destroy]
  resources :hospitals

end

app/models/hospital.rb
class Hospital < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :doctors
  has_many :categorizations
  has_many :departments, through: :categorizations
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, :name_kana, :founder, :founder_kana, :administer, :administer_kana, :post_code, :prefecture, :address, :phone_number, presence: true

  include JpPrefecture
  jp_prefecture :prefecture, method_name: :pref

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  before_action :authenticate_doctor!, only:[:new, :create, :edit, :update, :destroy]

  def index
    @q = Hospital.ransack(params[:q])
    @hospitals = @q.result(distinct: true).order(id: 'desc').paginate(page: params[:page], per_page: 5)
    @top = "医療機関一覧"
    if params[:q].present?
      if params[:q][:prefecture_eq].present? && params[:q][:departments_id_eq].present?
        @top = params[:q][:prefecture_eq] + "で" + Department.find(params[:q][:departments_id_eq]).name + "が受診できる医療機関"
      elsif params[:q][:prefecture_eq].present?
        @top = params[:q][:prefecture_eq] + "の医療機関"
      elsif params[:q][:departments_id_eq].present?
        @top = Department.find(params[:q][:departments_id_eq]).name + "の受診ができる医療機関"
      end
    else
      @top = "医療機関一覧"
    end
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
      current_doctor.hospital_id = @hospital.id
      current_doctor.save
      redirect_to @hospital
    else
      render :new
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
    if @hospital.doctors.where(id: current_doctor.id).empty?
      redirect_to @hospital
    end
  end

  def update
    @hospital = Hospital.find(params[:id])
    if @hospital.update(hospital_params)
      redirect_to @hospital
    else
      render :edit
    end
  end

  def destroy
    hospital = Hospital.find(params[:id])
    hospital.destroy
  end

  private
    def hospital_params
      params.require(:hospital).permit(:name, :name_kana, :founder, :founder_kana, :administer, :administer_kana, :post_code, :prefecture, :address, :phone_number, :homepage, :description, :image, { department_ids:[] })
    end
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/views/hospitals/_form.html.erb
<div class="hospital-new__box">
  <p class="post-form__icon fas fa-hospital fa-4x"></p>
  <h1 class="post-form__title"><%= title %></h1>

  <%= form_with model: obj, local: true do |f| %>

    <%= render "devise/shared/error_messages", resource: obj %>

    <div class="field">
      <%= f.text_field :name, autofocus:true, autocomplete: "name", placeholder: '病院名' %>
      <%= f.label :name, '病院名', class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :name_kana, autocomplete: "family_name", placeholder: '病院フリガナ' %>
      <%= f.label :name_kana, '病院フリガナ', class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :founder, autocomplete: "founder", placeholder: '開設者名' %>
      <%= f.label :founder, '開設者名', class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :founder_kana, autocomplete: "founder_kana", placeholder: '開設者名カナ' %>
      <%= f.label :founder_kana, '開設者名カナ', class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :administer, autocomplete: "administer", placeholder: '管理者名' %>
      <%= f.label :administer, '管理者名', class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :administer_kana, autocomplete: "administer_kana", placeholder: "管理者フリガナ" %>
      <%= f.label :administer_kana, "管理者フリガナ", class:"label" %>
    </div>

    <div class="field">
      <%= f.number_field :post_code, autocomplete: "post_code", placeholder: "郵便番号" %>
      <%= f.label :post_code, "郵便番号", class:"label" %>
    </div>

    <div class="field">
      <%= f.collection_select :prefecture, JpPrefecture::Prefecture.all, :name, :name, include_blank: "選択してください", class:"address" %>
      <%= f.label :prefecture, "都道府県", class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :address, autocomplete: "address", placeholder: "住所" %>
      <%= f.label :address, "住所", class:"label" %>
    </div>

    <div class="field">
      <%= f.telephone_field :phone_number, autocomplete: "phone_number", placeholder: "電話番号" %>
      <%= f.label :phone_number, "電話番号", class:"label" %>
    </div>

    <div class="field">
      <%= f.url_field :homepage, autocomplete: "homepage", placeholder: "ホームページ" %>
      <%= f.label :homepage, "ホームページ", class:"label" %>
    </div>

    <div class="prof__text-area__wrapper">
      <div class="field">
        <%= f.text_area :description, autocomplete: "description", placeholder: "病院説明等" %>
        <%= f.label :description, "病院説明等", class:"label" %>
      </div>
    </div>

    <div class="field">
      <%= f.file_field :image, autocomplete: "image", placeholder: "病院画像" %>
      <%= f.label :image, "病院画像", class:"label" %>
    </div>

    <div class="checkbox-field">
      <%= f.collection_check_boxes(:department_ids, Department.all, :id, :name) do |b| %>
        <div class="checkbox">
          <%= b.check_box(class: "check_box") %>
          <%= b.label do %>
            <%= b.object.name %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="field">
      <%= f.submit button, class:"button-default" %>
    </div>
  <% end %>
</div>

app/views/hospitals/_hospital.html.erb
<%= link_to hospital_path(hospital) do %>
  <div class="hospital-list">
    <%= image_tag hospital.image.to_s, class:"hospital-list__image" %>
    <div class="hospital-list__text">
      <h1 class="hospital-list__text__name"><%= hospital.name %></h1>
      <h2 class="hospital-list__text__address"><%= hospital.prefecture + hospital.address %></h2>
      <p class="hospital-list__text__description"><%= hospital.description %></p>
      <div class="hospital-list__text__department-box">
        <% hospital.departments.each do |department| %>
          <span class="hospital-list__text__department tag">
            <%= department.name %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/hospitals/_search.html.erb
<div class="hospital-search__container">
  <p class="search-form__text"><span>医療機関を検索</span><p>
  <%= search_form_for @q, url: hospitals_path do |f| %>
    <div class="field">
      <%= f.collection_select :prefecture_eq, JpPrefecture::Prefecture.all, :name, :name, include_blank: "都道府県を選択", class:"address" %>
      <%= f.label :prefecture, "都道府県", class:"label" %>
    </div>

    <div class="field">
      <%= f.collection_select :departments_id_eq, Department.all, :id, :name, include_blank: "診療科を選択" %>
      <%= f.label :department, "診療科", class:"label" %>
    </div>

    <div class="field" style="margin-top:2rem;">
      <%= f.submit "医療機関を検索", name: nil, class:"button-default" %>
    </div>
  <% end %>
</div>

app/views/hospitals/edit.html.erb
<div class="hospital-container">
  <div class="hospital-main">
    <div class="hospital-main__left">
      <%= render 'hospitals/form', obj: @hospital, title:'登録情報変更', button:'登録情報変更' %>
    </div>

    <div class="hospital-main__right">
      <%= render 'hospitals/search' %>
    </div>
  </div>
</div>

app/views/hospitals/index.html.erb
<div class="hospital-container">
  <div class="hospital-show">
    <div class="hospital-show__intro">
      <%= image_tag "dna.jpg", class:"hospital-show__image" %>
      <div class="hospital-show__text">
        <p class="hospital-show__name">
          <%= @top %>
        </p>
        </p>
      </div>
    </div>
  </div>
  <div class="hospital-main">
    <div class="hospital-main__left">
      <%= render @hospitals %>
      <%= will_paginate @hospitals, previous_label:'&lt ', next_label:' &gt', inner_window: 1, outer_window: 0 %>
    </div>
    <div class="hospital-main__right">
      <%= render 'hospitals/search' %>
    </div>
  </div>
</div>

app/views/hospitals/new.html.erb
<div class="hospital-container">
  <div class="hospital-main">
    <div class="hospital-main__left">
      <%= render 'hospitals/form', obj: @hospital, title:'医療機関新規登録', button:'新規登録' %>
    </div>

    <div class="hospital-main__right">
      <%= render 'hospitals/search' %>
    </div>
  </div>
</div>

app/views/hospitals/show.html.erb
<div class="hospital-container">
  <div class="hospital-show">
    <div class="hospital-show__intro">
      <%= image_tag @hospital.image.to_s, class:"hospital-show__image" %>
      <div class="hospital-show__text">
        <h1 class="hospital-show__name"><%= @hospital.name %></h1>
        <p class="hospital-show__address"><%= @hospital.prefecture + @hospital.address %></p>
      </div>
    </div>
  </div>
  <div class="hospital-main">
    <div class="hospital-main__left">
      <div class="hospital-show__detail">
        <div class="hospital-show__department-box">
          <% @hospital.departments.each do |department| %>
            <span class="hospital-show__department tag">
              <%= department.name %>
            </span>
          <% end %>
        </div>
        <div class="hospital-show__description">
          <p><%= simple_format @hospital.description %></p>
        </div>
        <div class="hospital-show__doctors">
          <h5 class="hospital-show__doctors-info">所属医師</h5>
          <% @hospital.doctors.each do |doctor| %>
            <%= link_to doctor_path(doctor) do %>
            <div class="hospital-show__doctor">
              <%= image_tag doctor.image.thumb.to_s, class:"hospital-show__doctor-image" %>
              <p class="hospital-show__doctor-name"><%= doctor.family_name + " " + doctor.first_name %><br/><small><%= doctor.department.name %></small></p>
            </div>
            <% end %>
          <% end %>
        </div>
        <div class="hospital-show__info">
          <h5 class="hospital-show__info-text">詳細情報</h5>
          <div id='hospital-show__map'></div>
          <script type="text/javascript">
            handler = Gmaps.build('Google');
            handler.buildMap({ provider: { scrollwheel: false }, internal: {id: 'hospital-show__map'}}, function(){
              markers = handler.addMarkers([
                {
                  "lat": <%= @hospital.latitude %>,
                  "lng": <%= @hospital.longitude %>,
              "infowindow": '<p><%= @hospital.name %></p><p><%= @hospital.address %></p><p><%= link_to "Googleマップで見る" ,"https://maps.google.co.jp/maps?q=loc:#{@hospital.latitude},#{@hospital.longitude}&iwloc=J",target: "_blank" %></p>'
                }
              ]);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              handler.getMap().setZoom(17);
            });
          </script>
          <p><i class="fas fa-hospital fa-fw"></i> <%= @hospital.founder %> <%= @hospital.name %></p>
          <p><i class="fas fa-user-md fa-fw"></i> <%= @hospital.administer %></p>
          <p><i class="fas fa-map-marker-alt fa-fw"></i> <%= @hospital.post_code + ' ' + @hospital.prefecture + @hospital.address %></p>
          <p><i class="fas fa-phone-alt fa-fw"></i> <%= @hospital.phone_number %></p>
          <% if @hospital.homepage.present? %>
            <%= link_to @hospital.homepage do %><i class="fas fa-globe fa-fw"></i> <%= @hospital.homepage %>
            <% end %>
          <% end %>
        </div>
        <% if doctor_signed_in? %>
          <% if @hospital.doctors.where(id: current_doctor.id).present? %>
            <%= link_to edit_hospital_path(@hospital), class:"hospital-show__edit" do %>
              <p class="icon-round"><i class=" fas fa-wrench"></i></p>
            <% end %>
          <% end %>
          <% if current_doctor.hospital.nil? %>
            <%= form_with model: current_doctor, local: true do |f| %>
              <%= f.hidden_field :hospital_id, value: @hospital.id %>
              <%= f.submit '所属する', class:"button-default" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="hospital-main__right">
      <%= render "hospitals/search" %>
    </div>
  </div>
</div>