config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, only: %i[sign_in sign_out session]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get 'about', to: 'home#about'
  get '/infiniteScrolling', to: "posts#infiniteScrolling"

  devise_for :doctors, controolers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    passwords: 'patients/passwords',
    registrations: 'patients/registrations'
  }

  resource :patient, only: %i[show]
  resources :doctors, only: %i[show update]
  resources :posts
  resources :opinions, :patient_comments, :doctor_comments, only: %i[create update destroy]
  resources :hospitals

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :hospital
  belongs_to :department
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :categorizations
  has_many :hospitals, through: :categorizations
  has_many :posts
  has_many :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :opinions
  has_many :doctor_comments
  belongs_to :department
  belongs_to :hospital, optional: true

  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, :registration_number, :registration_date, presence: true
end

app/models/doctor_comment.rb
class DoctorComment < ApplicationRecord
  belongs_to :doctor
  belongs_to :opinion

  validates :content, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :doctors
  has_many :categorizations
  has_many :departments, through: :categorizations
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, :name_kana, :founder, :founder_kana, :administer, :administer_kana, :post_code, :prefecture, :address, :phone_number, presence: true

  include JpPrefecture
  jp_prefecture :prefecture, method_name: :pref

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :post
  belongs_to :doctor
  has_many :doctor_comments
  has_many :patient_comments

  validates :content, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts
  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, presence: true
  validates :phone_number, length: { in: 10..13 }
end

app/models/patient_comment.rb
class PatientComment < ApplicationRecord
  belongs_to :patient
  belongs_to :opinion

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :patient
  belongs_to :department
  has_many :opinions
  mount_uploaders :refferal, ImageUploader
  serialize :refferal, JSON

  validates :refferal, :desease_name, :detail, presence: true
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  def show
    @doctor = Doctor.find(params[:id])
  end

  def update
    current_doctor.update(doctor_params)
    redirect_to current_doctor
  end

  private
    def doctor_params
      params.require(:doctor).permit(:hospital_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true
class PostsController < ApplicationController
  before_action :authenticate_patient!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(id: "desc").paginate(page: params[:page], per_page: 5)
    @top = "オピニオン依頼一覧"
    if params[:q].present?
      if params[:q][:department_id_eq].present?
      @top = Department.find(params[:q][:department_id_eq]).name + "のオピニオン依頼"
      end
    else
      @top = "オピニオン依頼一覧"
    end
  end

  def show
    @post = Post.find(params[:id])
    @q = Post.ransack(params[:q])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.patient_id = current_patient.id
    @post.department_id = 1
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def infiniteScrolling
    @posts = Post.all.paginate(page: params[:page], per_page: 5)
    respond_to do |format|
      format.js
    end
  end

  private
    def post_params
      params.require(:post).permit(:desease_name, :detail, :patient_id, :department_id, refferal: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctor_comments_helper.rb
module DoctorCommentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

  def age
    d1=self.date_of_birth.strftime("%Y%m%d").to_i
    d2=Date.today.strftime("%Y%m%d").to_i
    return (d2 - d1) / 10000
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_form.html.erb
<% if doctor_signed_in? %>
  <%= form_with model: DoctorComment.new, local: true do |c| %>
    <p>医師コメント内容<%= c.text_area :content %></p>
    <%= c.hidden_field :opinion_id, value: opinion.id %>
    <%= c.submit '送信' %>
  <% end %>
<% elsif patient_signed_in? %>
  <%= form_with model: PatientComment.new, local: true do |c| %>
    <p>患者コメント内容<%= c.text_area :content %></p>
    <%= c.hidden_field :opinion_id, value: opinion.id %>
    <%= c.submit '送信' %>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="post-form__box">

  <p class="post-form__icon fas fa-laptop-medical fa-4x"></p>
  <h1 class="post-form__title">セカンドオピニオン<%= title %></h1>
  <p class="post-form__text">できるだけ詳しくお書きください。</p>

  <%= form_with model: obj,  local: true do |f| %>

    <%= render "devise/shared/error_messages", resource: obj %>

    <div class="field">
      <%= f.file_field :refferal, multiple: true %>
      <%= f.label :refferal, "紹介状、検査資料など（複数可能）", class:"label" %>
    </div>

    <div class="field">
      <%= f.text_field :desease_name, autocomplete:"desease_name", placeholder: "病名" %>
      <%= f.label :desease_name, "病名", class:"label" %>
    </div>

    <div class="field">
      <%= f.collection_select(:name, Department.all, :id, :name) %>
      <%= f.label :name, "担当科", class:"label" %>
    </div>

    <div class="prof__text-area__wrapper">
      <div class="field">
        <%= f.text_area :detail, autocomplete:"detail", placeholder:"症状詳細等" %>
        <%= f.label :detail, "病状の詳細、聞きたいことなど", class:"label" %>
      </div>
    </div>

    <div class="field">
      <%= f.submit button, class:"button-default" %>
    </div>

  <% end %>

</div>

app/views/posts/_post.html.erb
<div class="post">
  <%= link_to post_path(post) do %>
    <div class="post-index__box">
        <div class="post-info">
          <h1 class="post-info__desease-name"><%= post.desease_name %></h1>
          <h5 class="post-info__name"><%= post.patient.family_name + ' ' + post.patient.first_name %></h5>
          <p class="post-info__time"><%= post.created_at.to_s(:datetime) %></p>
          <span class="post-info__department tag"><%= post.department.name %></span>
          <p class="post-info__detail"><%= post.detail %></p>
          <div class="post-index__refferal">
            <%= image_tag post.refferal.first.url %>
          </div>
        </div>
      <div class="post-bottom">
        <div class="post-bottom__comment-size"><i class="far fa-comment"></i>　<%= post.opinions.size %></div>
        <div class="post-bottom__button"><div class="post-button">みる</div></div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_search.html.erb
<div class="hospital-search__container">
  <p class="search-form__text"><span>オピニオン依頼を検索</span></p>
  <%= search_form_for @q do |f| %>

    <div class="field">
      <%= f.collection_select :department_id_eq, Department.all, :id, :name, include_blank: "診療科を選択" %>
      <%= f.label :department, "診療科", class:"label" %>
    </div>

    <div class="field" style="margin-top:2rem;">
      <%= f.submit "オピニオン依頼を検索", name: nil, class:"button-default" %>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'posts/form', title:'編集', obj: @post, button:'セカンドオピニオン依頼を編集する' %>

app/views/posts/index.html.erb
<div class="post-container">
  <div class="hospital-show">
    <div class="hospital-show__intro">
      <%= image_tag "dna.jpg", class:"hospital-show__image" %>
      <div class="hospital-show__text">
        <p class="hospital-show__name">
          <%= @top %>
        </p>
      </div>
    </div>
  </div>
  <div class="post-main">
    <div class="post-main__left">
      <div id="infiniteScrollingContainer">
        <%= render @posts %>
        <%= will_paginate @posts, previous_label:'&lt ', next_label:' &gt',inner_window: 1, outer_window: 0 %>
      </div>
    </div>
    <div class="post-main__right">
      <%= render 'posts/search'%>
    </div>
  </div>
</div>

<script>
$(document).on("turbolinks:load", function () {
  $("#infiniteScrollingContainer").on("scroll", function () {
    if (
      $("#infiniteScrollingContainer").scrollTop() +
        $("#infiniteScrollingContainer").height() ==
      $("#infiniteScrollingContainer")[0].scrollHeight - 16
    ) {
      alert("最後までスクロールしました！");
      setTimeout(function () {
        $.ajax({
          url: "/infiniteScrolling?page=2",
        });
      }, 500);
    }
  });
});
</script>

app/views/posts/infiniteScrolling.js.erb
$("#infiniteScrollingContainer").append("<%= escape_javascript(render 'posts/post') %>");

app/views/posts/new.html.erb
<%= render 'posts/form', title:'依頼', obj: @post, button:'セカンドオピニオン依頼をする' %>

app/views/posts/show.html.erb
<div class="post-container">
  <div class="post-main">
    <div class="post-main__left">
      <div class="post-box">
        <div class="post-info">
          <h1 class="post-info__desease-name"><%= @post.desease_name %></h1>
          <h5 class="post-info__name"><%= @post.patient.family_name + ' ' + @post.patient.first_name %></h5>
          <p class="post-info__time"><%= @post.created_at.to_s(:datetime) %></p>
          <span class="post-info__department tag"><%= @post.department.name %></span>
          <p class="post-info__detail"><%= safe_join(@post.detail.split("\n"),tag(:br)) %></p>
          <div class="post-info__refferal">
            <% @post.refferal.each do |r| %>
              <%= link_to r.url, 'data-lightbox' => @post, class:"post-info__lightbox" do %>
                <%= image_tag r.url %>
              <% end %>
            <% end %>
          </div>
        </div>
        <% if doctor_signed_in? %>
          <% if Opinion.find_by(post_id: params[:id], doctor_id: current_doctor.id).nil? %>
            <p class="post-info__comment-box">
              <span>セカンドオピニオンを投稿する</span>
              <span class="opinion__toggle comment-button"><i class="fas fa-edit"></i></span>
            </p>
            <div class="opinion__form form-toggle text-area__wrapper">
              <%= form_with model: Opinion.new, local: true do |f| %>
                <div class="field">
                  <%= f.text_area :content, placeholder: "セカンドオピニオン内容" %>
                  <%= f.label :content, "セカンドオピニオン内容", class:"label" %>
                </div>
                  <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.submit '送信', class:"button-default" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
        <%= render @post.opinions %>
        <% if patient_signed_in? %>
          <% if @post.patient == current_patient %>
            <%= link_to edit_post_path(@post), class:"post-info__edit" do %>
              <p class="icon-round"><i class=" fas fa-user-edit"></i></p>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="post-main__right">
      <%= render 'posts/search' %>
    </div>
  </div>
</div>

<script>
  $('.opinion__toggle').click(function() {
      $('.opinion__form').slideToggle(10);
  })
</script>