config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins, only: %i[sign_in sign_out session]
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get 'about', to: 'home#about'
  get '/infiniteScrolling', to: "posts#infiniteScrolling"

  devise_for :doctors, controolers: {
    sessions: 'doctors/sessions',
    passwords: 'doctors/passwords',
    registrations: 'doctors/registrations'
  }

  devise_for :patients, controllers: {
    sessions: 'patients/sessions',
    passwords: 'patients/passwords',
    registrations: 'patients/registrations'
  }

  resource :patient, only: %i[show]
  resources :doctors, only: %i[show update]
  resources :posts
  resources :opinions, :patient_comments, :doctor_comments, only: %i[create update destroy]
  resources :hospitals

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :hospital
  belongs_to :department
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :categorizations
  has_many :hospitals, through: :categorizations
  has_many :posts
  has_many :doctors
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  has_many :opinions
  has_many :doctor_comments
  belongs_to :department
  belongs_to :hospital, optional: true

  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, :registration_number, :registration_date, presence: true
end

app/models/doctor_comment.rb
class DoctorComment < ApplicationRecord
  belongs_to :doctor
  belongs_to :opinion

  validates :content, presence: true
end

app/models/hospital.rb
class Hospital < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :doctors
  has_many :categorizations
  has_many :departments, through: :categorizations
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, :name_kana, :founder, :founder_kana, :administer, :administer_kana, :post_code, :prefecture, :address, :phone_number, presence: true

  include JpPrefecture
  jp_prefecture :prefecture, method_name: :pref

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :post
  belongs_to :doctor
  has_many :doctor_comments
  has_many :patient_comments

  validates :content, presence: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable

  has_many :posts
  enum gender: { male: 0, female: 1}

  validates :family_name, :first_name, :family_name_kana, :first_name_kana, :gender, :date_of_birth, presence: true
  validates :phone_number, length: { in: 10..13 }
end

app/models/patient_comment.rb
class PatientComment < ApplicationRecord
  belongs_to :patient
  belongs_to :opinion

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :patient
  belongs_to :department
  has_many :opinions
  mount_uploaders :refferal, ImageUploader
  serialize :refferal, JSON

  validates :refferal, :desease_name, :detail, presence: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

  def age
    d1=self.date_of_birth.strftime("%Y%m%d").to_i
    d2=Date.today.strftime("%Y%m%d").to_i
    return (d2 - d1) / 10000
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_doctor_header.html.erb
<li class="nav-list__content"><%= link_to root_path, class:"top-title" do %>Re:MEDICAL<% end %></li>
<li class="nav-list__content"><%= link_to posts_path, class:"header-content" do %>投稿一覧<% end %></li>
<% if current_doctor.hospital_id.present? %>
  <li class="nav-list__content"><%= link_to hospital_path(current_doctor.hospital_id), class:"header-content" do %>所属病院<% end %></li>
<% else %>
  <li class="nav-list__content"><%= link_to new_hospital_path, class:"header-content" do %>所属病院登録<% end %></li>
<% end %>
<li class="nav-list__content"><%= link_to doctor_path(current_doctor), class:"top-button" do %>マイページ<% end %></li>
<li class="nav-list__content"><%= link_to destroy_doctor_session_path, class:"header-content", method: :delete do %>ログアウト<% end %></li>

app/views/layouts/_footer.html.erb
<footer class="footer">

  <%= render 'layouts/footer_nav' %>
  <%= render 'layouts/footer_contents' %>
  Copylight © Re:MEDICAL All rights reserved.
</footer>

app/views/layouts/_footer_contents.html.erb
<div class="footer-contents">

  <div class="footer-content">
    <div class="footer-content__text">
      <div class="footer-content__title">
        <p>制作者情報</p>
      </div>
      <ul>
        <li>
          片山 泰大<small> (カタヤマ タイスケ)</small>
        </li>
        <li>
          大阪府岸和田市
        </li>
        <li>
          HTML/CSS, Ruby/Ruby on Rails, JavaScript/React
        </li>
        <li>

        </li>
      </ul>
    </div>
  </div>

  <div class="footer-content">
    <div class="footer-content__text">
      <div class="footer-content__title">
        <p>コンテンツ一覧</p>
      </div>
      <ul>
        <li>
          <%= link_to 'トップページ', root_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to 'このサイトについて', about_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '患者様ログインページ', new_patient_session_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '医師ログインページ', new_doctor_session_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '患者様新規登録', new_patient_registration_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '医師新規登録', new_doctor_registration_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '医療機関新規登録', new_hospital_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to '医療機関一覧', hospitals_path, class:"footer-link" %>
        </li>
        <li>
          <%= link_to 'セカンドオピニオン一覧', posts_path, class:"footer-link" %>
        </li>
        <li>
          <% if patient_signed_in? %>
            <%= link_to 'マイページ', patient_path, class:"footer-link" %>
          <% elsif doctor_signed_in? %>
            <%= link_to 'マイページ', doctor_path(current_doctor), class:"footer-link" %>
          <% end %>
        </li>
        <li>
        </li>
      </ul>
    </div>
  </div>

  <div class="footer-content">
    <div class="footer-content__text">
      <div class="footer-content__title">
        <p>このサイトについて</p>
      </div>
      <ul>
        <li>
          利用規約
        </li>
        <li>
          プライバシーポリシー
        </li>
        <li>
          制作者
        </li>
      </ul>
    </div>
  </div>

</div>

app/views/layouts/_footer_nav.html.erb
<div class="footer-nav">
  <ul class="footer-nav__list">
    <li>
      <%if doctor_signed_in? %>
        <%= link_to "セカンドオピニオン一覧", posts_path, class:"footer-nav__content" %>
      <% elsif patient_signed_in? %>
        <%= link_to "セカンドオピニオン依頼", new_post_path, class:"footer-nav__content" %>
      <% else %>
        <%= link_to "セカンドオピニオン一覧", posts_path, class:"footer-nav__content" %>
      <% end %>
    </li>
    <li>
      <%= link_to "医療機関を探す", hospitals_path, class:"footer-nav__content" %>
    </li>
    <li>
      <% if doctor_signed_in? %>
        <%= link_to "マイページ", doctor_path(current_doctor), class:"footer-nav__content" %>
      <% elsif patient_signed_in? %>
        <%= link_to "マイページ", patient_path, class:"footer-nav__content" %>
      <% else %>
        <%= link_to "ログイン", root_path, class:"footer-nav__content" %>
      <% end %>
    </li>
  </ul>
</div>

app/views/layouts/_footer_search.html.erb
エリアで探す
<div class="footer-search__prefecture">
  <dl>
    <dt>北海道・東北</dt>
    <dd>
      <%= link_to '北海道', hospitals_path(params:{q:{prefecture_eq: '北海道'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '青森県', hospitals_path(params:{q:{prefecture_eq: '青森県'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '岩手県', hospitals_path(params:{q:{prefecture_eq: '岩手県'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '宮城県', hospitals_path(params:{q:{prefecture_eq: '宮城県'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '秋田県', hospitals_path(params:{q:{prefecture_eq: '秋田県'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '山形県', hospitals_path(params:{q:{prefecture_eq: '山形県'}}), class:"footer-link" %>
    </dd>
    <dd>
      <%= link_to '福島県', hospitals_path(params:{q:{prefecture_eq: '福島県'}}), class:"footer-link" %>
    </dd>
  </dl>

app/views/layouts/_guest_header.html.erb
<li class="nav-list__content"><%= link_to root_path, class:"top-title" do %>Re:MEDICAL<% end %></li>
<li class="nav-list__content"><%= link_to about_path, class:"header-content" do %>このサイトについて<% end %></li>
<li class="nav-list__content"><%= link_to new_patient_session_path, class:"header-content" do %>ログイン<% end %></li>
<li class="nav-list__content"><%= link_to new_patient_registration_path, class:"top-button" do %>新規登録<% end %></li>
<li class="nav-list__content"><%= link_to new_doctor_session_path, class:"header-content" do %>医療機関の方<% end %></li>

app/views/layouts/_hamburger_menu.html.erb
  <nav class="burger-nav">
    <ul class="burger-nav__list">
      <li class="burger-nav__item burger-title">Re:MEDICAL</li>
      <% if doctor_signed_in? %>
        <li class="burger-nav__item"><%= link_to posts_path, class:"header-content" do %>セカンドオピニオン依頼一覧<% end %></li>
        <li class="burger-nav__item"><%= link_to hospitals_path, class:"header-content" do %>医療機関一覧<% end %></li>
        <% if current_doctor.hospital_id.present? %>
          <li class="burger-nav__item"><%= link_to hospital_path(current_doctor.hospital_id), class:"header-content" do %>所属医療機関<% end %></li>
        <% else %>
          <li class="burger-nav__item"><%= link_to new_hospital_path, class:"header-content" do %>所属医療機関登録<% end %></li>
        <% end %>
        <li class="burger-nav__item"><%= link_to doctor_path(current_doctor), class:"top-button" do %>マイページ<% end %></li>
        <li class="burger-nav__item"><%= link_to destroy_doctor_session_path, class:"header-content", method: :delete do %>ログアウト<% end %></li>
      <% elsif patient_signed_in? %>
        <li class="burger-nav__item"><%= link_to new_post_path, class:"header-content" do %>新規セカンドオピニオン依頼<% end %></li>
        <li class="burger-nav__item"><%= link_to posts_path, class:"header-content" do %>セカンドオピニオン依頼一覧<% end %></li>
        <li class="burger-nav__item"><%= link_to hospitals_path, class:"header-content" do %>医療機関一覧<% end %></li>
        <li class="burger-nav__item"><%= link_to patient_path, class:"top-button" do %>マイページ<% end %></li>
        <li class="burger-nav__item"><%= link_to destroy_patient_session_path, class:"header-content", method: :delete do %>ログアウト<% end %></li>
      <% else %>
        <li class="burger-nav__item"><%= link_to about_path, class:"header-content" do %>このサイトについて<% end %></li>
        <li class="burger-nav__item"><%= link_to posts_path, class:"header-content" do %>セカンドオピニオン依頼一覧<% end %></li>
        <li class="burger-nav__item"><%= link_to hospitals_path, class:"header-content" do %>医療機関一覧<% end %></li>
        <li class="burger-nav__item"><%= link_to new_patient_session_path, class:"header-content" do %>ログイン<% end %></li>
        <li class="burger-nav__item"><%= link_to new_patient_registration_path, class:"top-button" do %>新規登録<% end %></li>
        <li class="burger-nav__item"><%= link_to new_doctor_session_path, class:"header-content" do %>医療機関の方<% end %></li>

      <% end %>
    </ul>
  </nav>
  <div class="hamburger" id="js-hamburger">
    <span class="hamburger__line hamburger__line-1"></span>
    <span class="hamburger__line hamburger__line-2"></span>
    <span class="hamburger__line hamburger__line-3"></span>
  </div>
  <div class="black-bg" id="js-black-bg"></div>

<script>
  function toggleNav() {
    var body = document.body;
    var hamburger = document.getElementById("js-hamburger");
    var blackBg = document.getElementById("js-black-bg");

    hamburger.addEventListener("click", function () {
      body.classList.toggle("nav-open");
    });
    blackBg.addEventListener("click", function () {
      body.classList.remove("nav-open");
    });
  }
  toggleNav();
</script>

app/views/layouts/_header.html.erb
<header class="header">
  <nav class="nav">
    <ul class="nav-list">
      <% if doctor_signed_in? %>
        <%= render '/layouts/doctor_header' %>
      <% elsif patient_signed_in? %>
        <%= render '/layouts/patient_header' %>
      <% else %>
        <%= render '/layouts/guest_header' %>
      <% end %>
    </ul>
  </nav>
  <%= link_to root_path, class:"header-logo" do %>Re:MEDICAL<% end %>
  <%= render 'layouts/hamburger_menu' %>
</header>

app/views/layouts/_patient_header.html.erb
<li class="nav-list__content"><%= link_to root_path, class:"top-title" do %>Re:MEDICAL<% end %></li>
<li class="nav-list__content"><%= link_to posts_path, class:"header-content" do %>投稿一覧<% end %></li>
<li class="nav-list__content"><%= link_to patient_path, class:"top-button" do %>マイページ<% end %></li>
<li class="nav-list__content"><%= link_to destroy_patient_session_path, class:"header-content", method: :delete do %>ログアウト<% end %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReMedical</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-autosize@1.18.18/jquery.autosize.min.js"></script>
  </head>

  <body ontouchstart="">
    <%= render '/layouts/header' %>
      <%= yield %>
    <%= render '/layouts/footer' %>

    <script>
      $(function(){
        $('textarea').autosize();
      });
    </script>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReMedical</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap" rel="stylesheet">
        <link
      href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900"
      rel="stylesheet"
    />
  </head>

  <body ontouchstart="">
      <%= yield %>
  </body>
</html>